--
-- PostgreSQL database dump
--

-- Dumped from database version 13.2
-- Dumped by pg_dump version 13.2

-- Started on 2021-05-28 19:41:45

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 212 (class 1259 OID 16894)
-- Name: cities; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cities (
    id integer NOT NULL,
    city character varying(255) NOT NULL
);


ALTER TABLE public.cities OWNER TO postgres;

--
-- TOC entry 202 (class 1259 OID 16570)
-- Name: employees; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.employees (
    user_id integer NOT NULL,
    first_name character varying(10) NOT NULL,
    last_name character varying(10) NOT NULL
);


ALTER TABLE public.employees OWNER TO postgres;

--
-- TOC entry 201 (class 1259 OID 16567)
-- Name: employers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.employers (
    user_id integer NOT NULL,
    website character varying(30) NOT NULL,
    phone_number integer NOT NULL,
    company_name character varying(30) NOT NULL,
    is_activated boolean
);


ALTER TABLE public.employers OWNER TO postgres;

--
-- TOC entry 207 (class 1259 OID 16627)
-- Name: hibernate_sequence; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.hibernate_sequence
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.hibernate_sequence OWNER TO postgres;

--
-- TOC entry 211 (class 1259 OID 16889)
-- Name: job_advertisements; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.job_advertisements (
    id integer NOT NULL,
    requirements character varying(150),
    city_id integer,
    open_positions integer,
    application_date date,
    application_deadline date,
    is_active boolean,
    employer_id integer,
    position_id integer,
    salary integer
);


ALTER TABLE public.job_advertisements OWNER TO postgres;

--
-- TOC entry 203 (class 1259 OID 16579)
-- Name: job_hunters; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.job_hunters (
    user_id integer NOT NULL,
    first_name character varying(20) NOT NULL,
    last_name character varying(20) NOT NULL,
    birth_date integer NOT NULL,
    national_identity character varying(11) NOT NULL,
    is_activated boolean
);


ALTER TABLE public.job_hunters OWNER TO postgres;

--
-- TOC entry 204 (class 1259 OID 16582)
-- Name: jobs; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.jobs (
    id integer NOT NULL,
    name character varying(20) NOT NULL
);


ALTER TABLE public.jobs OWNER TO postgres;

--
-- TOC entry 206 (class 1259 OID 16589)
-- Name: jobs_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.jobs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.jobs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 200 (class 1259 OID 16564)
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    user_id integer NOT NULL,
    password character varying(20) NOT NULL,
    email character varying(20) NOT NULL
);


ALTER TABLE public.users OWNER TO postgres;

--
-- TOC entry 205 (class 1259 OID 16587)
-- Name: users_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN user_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 210 (class 1259 OID 16874)
-- Name: verification_by_employees; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.verification_by_employees (
    id integer NOT NULL,
    employer_id integer,
    employee_id integer,
    confirm_date date
);


ALTER TABLE public.verification_by_employees OWNER TO postgres;

--
-- TOC entry 208 (class 1259 OID 16759)
-- Name: verification_codes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.verification_codes (
    id integer NOT NULL,
    confirm_date date,
    verification_code character varying(255),
    user_id integer
);


ALTER TABLE public.verification_codes OWNER TO postgres;

--
-- TOC entry 209 (class 1259 OID 16762)
-- Name: verification_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.verification_codes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.verification_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 2905 (class 2606 OID 16898)
-- Name: cities cities_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cities
    ADD CONSTRAINT cities_pkey PRIMARY KEY (id);


--
-- TOC entry 2893 (class 2606 OID 16602)
-- Name: employees employees_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employees
    ADD CONSTRAINT employees_pkey PRIMARY KEY (user_id);


--
-- TOC entry 2891 (class 2606 OID 16611)
-- Name: employers employers_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employers
    ADD CONSTRAINT employers_pkey PRIMARY KEY (user_id);


--
-- TOC entry 2903 (class 2606 OID 16893)
-- Name: job_advertisements job_advertisements_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.job_advertisements
    ADD CONSTRAINT job_advertisements_pkey PRIMARY KEY (id);


--
-- TOC entry 2895 (class 2606 OID 16609)
-- Name: job_hunters job_hunters_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.job_hunters
    ADD CONSTRAINT job_hunters_pkey PRIMARY KEY (user_id);


--
-- TOC entry 2897 (class 2606 OID 16595)
-- Name: jobs jobs_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.jobs
    ADD CONSTRAINT jobs_pkey PRIMARY KEY (id);


--
-- TOC entry 2889 (class 2606 OID 16586)
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (user_id);


--
-- TOC entry 2901 (class 2606 OID 16878)
-- Name: verification_by_employees verification_by_employees_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.verification_by_employees
    ADD CONSTRAINT verification_by_employees_pkey PRIMARY KEY (id);


--
-- TOC entry 2899 (class 2606 OID 16768)
-- Name: verification_codes verification_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.verification_codes
    ADD CONSTRAINT verification_pkey PRIMARY KEY (id);


--
-- TOC entry 2912 (class 2606 OID 16899)
-- Name: job_advertisements cities_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.job_advertisements
    ADD CONSTRAINT cities_id FOREIGN KEY (city_id) REFERENCES public.cities(id) NOT VALID;


--
-- TOC entry 2907 (class 2606 OID 16612)
-- Name: employees emplooyes_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employees
    ADD CONSTRAINT emplooyes_user_id FOREIGN KEY (user_id) REFERENCES public.users(user_id) NOT VALID;


--
-- TOC entry 2913 (class 2606 OID 16904)
-- Name: job_advertisements employer_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.job_advertisements
    ADD CONSTRAINT employer_id FOREIGN KEY (employer_id) REFERENCES public.employers(user_id) NOT VALID;


--
-- TOC entry 2906 (class 2606 OID 16617)
-- Name: employers employers_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employers
    ADD CONSTRAINT employers_user_id FOREIGN KEY (user_id) REFERENCES public.users(user_id) NOT VALID;


--
-- TOC entry 2908 (class 2606 OID 16622)
-- Name: job_hunters job_hunters_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.job_hunters
    ADD CONSTRAINT job_hunters_user_id FOREIGN KEY (user_id) REFERENCES public.users(user_id) NOT VALID;


--
-- TOC entry 2914 (class 2606 OID 16909)
-- Name: job_advertisements job_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.job_advertisements
    ADD CONSTRAINT job_id FOREIGN KEY (position_id) REFERENCES public.jobs(id) NOT VALID;


--
-- TOC entry 2911 (class 2606 OID 16884)
-- Name: verification_by_employees user_id_employer; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.verification_by_employees
    ADD CONSTRAINT user_id_employer FOREIGN KEY (employer_id) REFERENCES public.employers(user_id) NOT VALID;


--
-- TOC entry 2910 (class 2606 OID 16879)
-- Name: verification_by_employees user_id_empoyee; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.verification_by_employees
    ADD CONSTRAINT user_id_empoyee FOREIGN KEY (employee_id) REFERENCES public.employees(user_id) NOT VALID;


--
-- TOC entry 2909 (class 2606 OID 16869)
-- Name: verification_codes user_id_from_user; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.verification_codes
    ADD CONSTRAINT user_id_from_user FOREIGN KEY (user_id) REFERENCES public.users(user_id) NOT VALID;


-- Completed on 2021-05-28 19:41:46

--
-- PostgreSQL database dump complete
--

