--
-- PostgreSQL database dump
--

-- Dumped from database version 13.2
-- Dumped by pg_dump version 13.2

-- Started on 2021-05-10 14:07:19

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 202 (class 1259 OID 16570)
-- Name: employees; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.employees (
    user_id integer NOT NULL,
    first_name character varying(10) NOT NULL,
    last_name character varying(10) NOT NULL
);


ALTER TABLE public.employees OWNER TO postgres;

--
-- TOC entry 201 (class 1259 OID 16567)
-- Name: employers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.employers (
    user_id integer NOT NULL,
    website character varying(30) NOT NULL,
    phone_number integer NOT NULL,
    company_name character varying(30) NOT NULL
);


ALTER TABLE public.employers OWNER TO postgres;

--
-- TOC entry 208 (class 1259 OID 16747)
-- Name: employers_verification; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.employers_verification (
    id integer NOT NULL,
    activation_code character varying(20) NOT NULL,
    employer_user_id integer NOT NULL,
    confirmed_date date NOT NULL,
    confirm_by_mail boolean,
    confirm_by_employee boolean
);


ALTER TABLE public.employers_verification OWNER TO postgres;

--
-- TOC entry 207 (class 1259 OID 16627)
-- Name: hibernate_sequence; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.hibernate_sequence
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.hibernate_sequence OWNER TO postgres;

--
-- TOC entry 203 (class 1259 OID 16579)
-- Name: job_hunters; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.job_hunters (
    user_id integer NOT NULL,
    first_name character varying(20) NOT NULL,
    last_name character varying(20) NOT NULL,
    birth_date integer NOT NULL,
    national_identity character varying(15) NOT NULL
);


ALTER TABLE public.job_hunters OWNER TO postgres;

--
-- TOC entry 204 (class 1259 OID 16582)
-- Name: jobs; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.jobs (
    id integer NOT NULL,
    name character varying(20) NOT NULL
);


ALTER TABLE public.jobs OWNER TO postgres;

--
-- TOC entry 206 (class 1259 OID 16589)
-- Name: jobs_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.jobs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.jobs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 200 (class 1259 OID 16564)
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    user_id integer NOT NULL,
    password character varying(20) NOT NULL,
    email character varying(20) NOT NULL
);


ALTER TABLE public.users OWNER TO postgres;

--
-- TOC entry 205 (class 1259 OID 16587)
-- Name: users_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN user_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 2879 (class 2606 OID 16602)
-- Name: employees employees_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employees
    ADD CONSTRAINT employees_pkey PRIMARY KEY (user_id);


--
-- TOC entry 2877 (class 2606 OID 16611)
-- Name: employers employers_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employers
    ADD CONSTRAINT employers_pkey PRIMARY KEY (user_id);


--
-- TOC entry 2885 (class 2606 OID 16751)
-- Name: employers_verification employers_verification_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employers_verification
    ADD CONSTRAINT employers_verification_pkey PRIMARY KEY (id);


--
-- TOC entry 2881 (class 2606 OID 16609)
-- Name: job_hunters job_hunters_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.job_hunters
    ADD CONSTRAINT job_hunters_pkey PRIMARY KEY (user_id);


--
-- TOC entry 2883 (class 2606 OID 16595)
-- Name: jobs jobs_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.jobs
    ADD CONSTRAINT jobs_pkey PRIMARY KEY (id);


--
-- TOC entry 2875 (class 2606 OID 16586)
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (user_id);


--
-- TOC entry 2887 (class 2606 OID 16612)
-- Name: employees emplooyes_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employees
    ADD CONSTRAINT emplooyes_user_id FOREIGN KEY (user_id) REFERENCES public.users(user_id) NOT VALID;


--
-- TOC entry 2886 (class 2606 OID 16617)
-- Name: employers employers_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employers
    ADD CONSTRAINT employers_user_id FOREIGN KEY (user_id) REFERENCES public.users(user_id) NOT VALID;


--
-- TOC entry 2889 (class 2606 OID 16752)
-- Name: employers_verification employers_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employers_verification
    ADD CONSTRAINT employers_user_id FOREIGN KEY (employer_user_id) REFERENCES public.employers(user_id) NOT VALID;


--
-- TOC entry 2888 (class 2606 OID 16622)
-- Name: job_hunters job_hunters_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.job_hunters
    ADD CONSTRAINT job_hunters_user_id FOREIGN KEY (user_id) REFERENCES public.users(user_id) NOT VALID;


-- Completed on 2021-05-10 14:07:20

--
-- PostgreSQL database dump complete
--

